# ゼロから作るDeep Learning

## 1章 Python入門

### 1.5 Numpy

In [1]:
import numpy as np

#### 1.5.2 Numpy配列の生成

In [2]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)


[1. 2. 3.]


numpy.ndarray

#### 1.5.3 Numpyの算術計算

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y # 要素ごとの足し算

array([3., 6., 9.])

In [4]:
x - y

array([-1., -2., -3.])

In [8]:
x * y # element-wise product

array([ 2.,  8., 18.])

In [9]:
x / y

array([0.5, 0.5, 0.5])

In [11]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0  # ブロードキャスト

array([0.5, 1. , 1.5])

#### 1.5.4 NumpyのN次元配列

In [19]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [20]:
A.shape # 2 x 2

(2, 2)

In [21]:
A.dtype

dtype('int64')

In [22]:
B = np.array([[3, 0], [0,6]])

In [23]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [24]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [26]:
print(A)

[[1 2]
 [3 4]]


In [28]:
A * 10

array([[10, 20],
       [30, 40]])

#### 1.5.5 ブロードキャスト

In [32]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10,20])
A * B

array([[10, 40],
       [30, 80]])

#### 1.5.6 要素へのアクセス

In [33]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [34]:
X[0]

array([51, 55])

In [35]:
X[0][1]

55

In [36]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [37]:
X = X.flatten() # Xを1次元の配列へ変換
print(X)

[51 55 14 19  0  4]


In [38]:
X[np.array([0, 2, 4])]  # インデックスが0,2,4番目の要素を取得

array([51, 14,  0])

In [39]:
X > 15

array([ True,  True, False,  True, False, False])

In [41]:
X[X > 15] # Xが15より大きい要素の取得

array([51, 55, 19])