# ゼロから作るDeep Learning

## 3章 ニューラルネットワーク

### 3.3 多次元配列の計算

#### 3.3.1 多次元配列

In [1]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [4]:
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

1
(4,)
4


In [5]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)
print(np.ndim(B))
print(B.shape)


[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


#### 3.3.2 行列の積

In [2]:
import numpy as np
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [3]:
B = np.array([ [5,6], [7,8]])
B.shape

(2, 2)

In [4]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

In [5]:
A = np.array([[1,2,3], [4,5,6]])
A.shape

(2, 3)

In [6]:
B = np.array([[1,2], [3,4], [5,6]])
B.shape

(3, 2)

In [7]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [8]:
C = np.array([[1,2], [3,4]])
C.shape

(2, 2)

In [9]:
A.shape

(2, 3)

In [10]:

np.dot(A,C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

###　^^^ Aの1次元目とCの0次元目の要素数が一致しないのでエラーになる

$$
A(3*2) B(2) = C(3)
$$

In [11]:
A = np.array([[1,2], [3,4], [5,6]])
A.shape

(3, 2)

In [12]:
B = np.array([7,8])
B.shape

(2,)

In [13]:
np.dot(A, B)

array([23, 53, 83])

#### 3.3.3 ニューラルネットワークの行列の積

In [18]:
X = np.array([1,2])
print(X)
print(X.shape)
W = np.array([[1,3,5], [2,4,6]])
print(W)
print(W.shape)

[1 2]
(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [17]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
