# 3.3.3 ニューラルネットワークの行列の積

In [1]:
import numpy as np

In [2]:
X = np.array([1,2])

In [3]:
X.shape

(2,)

In [4]:
W = np.array([[1,3,5], [2,4,6]])

In [5]:
print(W)

[[1 3 5]
 [2 4 6]]


In [6]:
W.shape

(2, 3)

In [7]:
Y = np.dot(X, W)

In [8]:
print(Y)

[ 5 11 17]
