# 行列の積

In [7]:
import numpy as np

In [8]:
A = np.array([[1,2], [3,4]])

In [9]:
A.shape

(2, 2)

In [10]:
B = np.array([ [5,6], [7,8]])

In [11]:
B.shape

(2, 2)

In [12]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [13]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

In [14]:
A = np.array([[1,2,3], [4,5,6]])

In [15]:
A.shape

(2, 3)

In [16]:
B = np.array([[1,2], [3,4], [5,6]])

In [17]:
B.shape

(3, 2)

In [18]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [19]:
C = np.array([[1,2], [3,4]])

In [20]:
C.shape

(2, 2)

In [21]:
A.shape

(2, 3)

In [22]:

np.dot(A,C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

###　^^^ Aの1次元目とCの0次元目の要素数が一致しないのでエラーになる

$$
A(3*2) B(2) = C(3)
$$

In [23]:
A = np.array([[1,2], [3,4], [5,6]])

In [24]:
A.shape

(3, 2)

In [25]:
B = np.array([7,8])

In [26]:
B.shape

(2,)

In [27]:
np.dot(A, B)

array([23, 53, 83])