# 3.5.2 ソフトマックス関数の実装上の注意

$$
\frac{\exp(a_k)}{{\sum^n_{i=1}}\exp(a_i)}
$$


$$
y_k = \frac{\exp(a_k)}{{\sum_{i=1}^n}\exp(a_i)} \\
= \frac{C\exp(a_k)}{C{\sum_{i=1}^n}\exp(a_i)} \\
= \frac{\exp(a_k + \log{C})}{{\sum_{i=1}^n}\ex
p(a_i+\log{C})} \\
= \frac{\exp(a_k + C')}{{\sum_{i=1}^n}\exp(a_i+C')} \\
$$

In [1]:
import numpy as np

In [2]:
a = np.array([1010, 1000, 990])

In [4]:
np.exp(a) / np.sum(np.exp(a))

/home/masaru/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.
/home/masaru/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,  nan,  nan])

In [5]:
c = np.max(a)

In [6]:
a - c

array([  0, -10, -20])

In [7]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

In [8]:
def softmax(a):
    c = np.max(a)
    exp_a = np.sum(exp_a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y